enable-magisk-update = true # set this to false if you do not want to receive up

[Music-RVX]
app-name = "Music"
build-mode = "both"
version = "7.08.53"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.227.0-dev.22"
integrations-version = "v0.154.0-dev.7"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = ""
included-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music' 'Amoled' 'Bitrate default value' 'Certificate spoof' 'Change start page' 'Disable auto captions' 'Disable dislike redirection' 'Enable debug logging' 'Enable landscape mode' 'Enable minimized playback' 'Enable opus codec' 'Flyout menu components' 'GmsCore support' 'Hide account components' 'Hide action bar components' 'Hide ads' 'Hide double tap overlay filter' 'Hide layout components' 'Hide overlay filter' 'Hide player overlay filter' 'Navigation bar components' 'Remove viewer discretion dialog' 'Player components' 'Replace cast button' 'Restore old style library shelf' 'Return YouTube Dislike' 'Sanitize sharing links' 'Settings' 'SponsorBlock' 'Spoof app version' 'Translations' 'Video playback'"
arch = "arm64-v8a"

[YouTube-RVX]
app-name = "YouTube"
build-mode = "both"
version = "19.25.39"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.227.0-dev.22"
integrations-version = "v0.154.0-dev.7"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = ""
included-patches = "'Shorts overlay buttons' 'Custom branding icon YouTube' 'Custom branding name YouTube' 'Add splash animation' 'Alternative thumbnails' 'Ambient mode control' 'Change player flyout menu toggles' 'Change shorts repeat state' 'Change start page' 'Custom double tap length' 'Description components' 'Disable QUIC protocol' 'Disable auto audio tracks' 'Disable auto captions' 'Disable haptic feedback' 'Disable resuming shorts on startup' 'Disable splash animation' 'Enable debug logging' 'Enable external browser' 'Enable external browser' 'Enable gradient loading screen' 'Enable minimized playback' Enable open links directly' 'Enable tablet mini player' 'Force snackbar theme' 'Fullscreen components' 'GmsCore support' 'Hide action buttons' 'Hide ads' 'Hide comments component' 'Hide double tap overlay filter' 'Overlay buttons'"
arch = "arm64-v8a"



[twitter-non-monet]
build-mode = "apk"
version = "10.43.0-release.0"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
patches-version = "v1.30.1"
integrations-version = "v1.19.1"
rv-brand = "Piko Patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
included-patches = "'Custom Navigation' 'Navigation bar items to hide' 'Download preference' 'Force enable translate' 'Hide promote button' 'Remove Ads' 'Remove Google Ads' 'Remove "Who to follow" Banner' 'Remove "Creators to subscribe" Banner' 'Remove "Communities to join" Banner' 'Remove "Pinned posts by followers" Banner' 'Remove "Revisit Bookmark" Banner' 'Remove Detailed posts' 'Hide Promoted Trends' 'Custom download folder' 'Clear tracking params' 'No shortened URL' 'Bring back twitter' 'Disable chirp font' 'Hide FAB' 'Hide FAB Menu Buttons' 'Hide Community Notes' 'Hide Recommended Users' 'Selectable Text' 'Show sensitive media' 'Adds settings' 'Remove view count' 'Hook feature flag' 'Enable custom app icon and nav icon settings' 'Enable Reader Mode' 'Enable Undo Posts' 'Download patch' 'Hide Banner' 'Hide For You' 'Hide Live Threads' 'Hide bookmark icon in timeline' 'Customize profile tabs' 'No shortened URL' 'Customize Inline action Bar items' 'Round off numbers' 'Hide hidden replies' 'Hide Buy Premium Banner'"
excluded-patches = "'Dynamic color'"
arch = "arm64-v8a"

[Reddit]
app-name = "Reddit"
version = "2024.17.0"
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
patches-version = "v2.227.0-dev.20"
integrations-version = "v0.154.0-dev.6"
included-patches = "'Disable screenshot popup' 'Hide ads' 'Hide navigation buttons' 'Hide recently visited shelf' 'Open links directly' 'Open links externally' 'Premium icon' 'Remove subreddit dialog' 'Sanitize sharing links' 'Settings'"
rv-brand = "RVX"
arch = "arm64-v8a"

