enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music-RVX]
app-name = "Music"
build-mode = "both"
version = "7.08.52"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.227.0-dev.14"
integrations-version = "v0.154.0-dev.5"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = ""
included-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
arch = "arm64-v8a"

[YouTube-RVX]
app-name = "YouTube"
build-mode = "both"
version = "19.25.32"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.227.0-dev.14"
integrations-version = "v0.154.0-dev.5"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Shorts overlay buttons'"
included-patches = "'Custom branding icon YouTube' 'Hide videos based on duration ' 'Force disable Shorts dim' 'Force snackbar theme' 'Custom branding name YouTube' 'Add splash animation' ' Insert position'"
arch = "arm64-v8a"


[twitter-non-monet]
build-mode = "apk"
version = "10.48.0-release.0"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
patches-version = "v1.31.2"
integrations-version = "v1.20.1"
rv-brand = "Piko Patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
included-patches = "'Remove "Creators to subscribe" Banner' 'Remove "Communities to join" Banner' 'Remove "Who to follow" Banner' 'Remove Google Ads' 'Remove Ads' 'Custom download folder' 'Hide Promoted Trends' 'Remove Detailed posts' 'Remove "Revisit Bookmark" Banner' 'Remove "Pinned posts by followers" Banner' 'Hide FAB' 'Disable chirp font' 'Bring back twitter' 'No shortened URL' 'Clear tracking params' 'Show sensitive media' 'Selectable Text' 'Hide Recommended Users' 'Hide Community Notes' 'Hide FAB Menu Buttons' 'Enable Reader Mode' 'Enable custom app icon and nav icon settings' 'Hook feature flag' 'Remove view count' 'Adds settings' 'Hide Live Threads' 'Hide For You' 'Hide Banner' 'Download patch' 'Enable Undo Posts' 'Hide bookmark icon in timeline'"
excluded-patches = "'Dynamic color'"
arch = "arm64-v8a"


[Reddit-Extended]
build-mode = "apk"
patches-source = "anddearevanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.227.0-dev.14"
integrations-version = "v0.154.0-dev.5"
included-patches = "'Disable screenshot popup' 'Hide ads' 'Hide navigation buttons' 'Remove subreddit dialog' 'Premium icon' 'Open links externally' 'Open links directly' 'Hide recently visited shelf' 'Settings' 'Sanitize sharing links'"
arch = "arm64-v8a"
